import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import GoogleAnalytics from "./components/GoogleAnalytics";
import UtmCapture from "./components/UtmCapture";
import { JsonLd, organizationSchema, localBusinessSchema } from "./lib/schema";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  // Default title for pages without their own metadata export.
  // Per SEO playbook §4.1: target ≤ 60 chars / ≤ 600px desktop.
  // Brand at the end matches the rest of the site's title convention.
  title: "Regenerative Revival | Advanced Stem Cell Therapy & Regenerative Medicine",
  // Per playbook §4.2: target 150-158 chars.
  description:
    "Wharton's Jelly stem cell therapy and regenerative medicine for pain relief, tissue repair, and recovery. Book your free consultation today.",
  keywords: [
    "stem cell therapy",
    "regenerative medicine",
    "Wharton's Jelly",
    "stem cell treatment",
    "pain relief",
    "tissue regeneration",
    "buy stem cells",
    "regenerative revival",
  ],
  alternates: {
    canonical: "https://www.regenerativerevival.com",
  },
  openGraph: {
    title: "Regenerative Revival | Advanced Stem Cell Therapy",
    description:
      "Cutting-edge Wharton's Jelly therapy for pain relief, tissue repair & recovery.",
    url: "https://www.regenerativerevival.com",
    siteName: "Regenerative Revival",
    type: "website",
    // OG images are now auto-generated by app/opengraph-image.tsx
    // (dynamic 1200x630 branded card — see SEO playbook §4.7 / §16.12).
    // Per-page metadata can still override via `openGraph.images`.
  },
  twitter: {
    card: "summary_large_image",
    title: "Regenerative Revival | Advanced Stem Cell Therapy",
    description:
      "Cutting-edge Wharton's Jelly therapy for pain relief, tissue repair & recovery.",
    // Twitter card uses the same auto-generated OG image (Next.js default).
  },
  ...(process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION && {
    verification: {
      google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
    },
  }),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${playfair.variable} antialiased`}
      >
        <GoogleAnalytics />
        <UtmCapture />
        <JsonLd data={organizationSchema()} />
        <JsonLd data={localBusinessSchema()} />
        <Navbar />
        {children}
        <Footer />
        {/* Vercel monitoring (playbook §9.8) — auto-enables once deployed */}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
